"""
Pydantic schemas and data types defining state, goal analysis, tasks, plans, tool IO,
tool calls, observations, evaluations, and output reports.
"""

from datetime import datetime, timezone
from enum import Enum
from typing import List, Dict, Any, Optional, Literal
from pydantic import BaseModel, Field


class TaskStatus(str, Enum):
    PENDING = "pending"
    IN_PROGRESS = "in_progress"
    COMPLETED = "completed"
    FAILED = "failed"
    RETRYING = "retrying"


class DecisionType(str, Enum):
    CONTINUE = "continue"
    RETRY = "retry"
    REPLAN = "replan"
    COMPLETE = "complete"
    FAIL = "fail"


class GoalAnalysis(BaseModel):
    """Structured breakdown of a user's high-level research goal."""
    objective: str = Field(description="Primary objective of the research request")
    topic: str = Field(description="Core domain or subject matter of the research")
    constraints: List[str] = Field(
        default_factory=list,
        description="Boundaries, filters, or specific scope limits (e.g. timeframes, level of detail)"
    )
    time_range: Optional[str] = Field(
        default=None,
        description="Temporal boundary if specified in the user request (e.g. 'last 7 days')"
    )
    output_requirements: List[str] = Field(
        default_factory=list,
        description="Required format, deliverables, or key sections requested"
    )
    success_criteria: List[str] = Field(
        default_factory=list,
        description="Specific verification criteria to determine when the research is complete"
    )


class ToolInput(BaseModel):
    """Explicit parameters for planned tool execution without open-ended dictionaries."""
    query: Optional[str] = Field(default=None, description="Search query string if invoking web_search")
    url: Optional[str] = Field(default=None, description="Target URL if invoking page_fetcher")
    max_results: Optional[int] = Field(default=5, description="Maximum number of search results to return")
    timeout_seconds: Optional[int] = Field(default=15, description="Network timeout in seconds")


class PlannedTask(BaseModel):
    """An individual task generated by the LLM planner with a closed schema."""
    id: str = Field(description="Unique identifier for the task, e.g. task_1")
    description: str = Field(description="Clear action-oriented task description")
    objective: str = Field(default="", description="Specific sub-goal this task aims to accomplish")
    expected_output: str = Field(default="", description="Description of expected deliverable/data from this step")
    suggested_tool: Literal["web_search", "page_fetcher"] = Field(
        default="web_search",
        description="Name of the tool suggested for executing this step"
    )
    dependencies: List[str] = Field(
        default_factory=list,
        description="IDs of prerequisite tasks that must be completed before this step"
    )
    tool_input: Optional[ToolInput] = Field(
        default_factory=ToolInput,
        description="Explicit parameters passed to the tool"
    )

    def to_runtime_task(self) -> "Task":
        """Converts the planned task into a runtime Task instance."""
        tool_input_dict = {}
        if self.tool_input:
            tool_input_dict = {
                k: v for k, v in self.tool_input.model_dump().items()
                if v is not None
            }
        return Task(
            id=self.id,
            description=self.description,
            objective=self.objective,
            expected_output=self.expected_output,
            suggested_tool=self.suggested_tool,
            dependencies=list(self.dependencies),
            tool_input=tool_input_dict,
        )


class LLMPlan(BaseModel):
    """Closed Pydantic schema for LLM plan generation, fully compatible with Gemini Developer API."""
    query: str = Field(description="Original research topic or query submitted by user")
    rationale: str = Field(description="Explanation of why this dynamic plan decomposition was selected")
    tasks: List[PlannedTask] = Field(default_factory=list, description="Sequence of subtasks to execute")

    def to_runtime_plan(self) -> "Plan":
        """Converts the LLMPlan into the runtime Plan model used by the execution loop."""
        return Plan(
            query=self.query,
            rationale=self.rationale,
            tasks=[t.to_runtime_task() for t in self.tasks],
            current_task_index=0,
        )


class Task(BaseModel):
    """An individual task within an autonomous execution plan."""
    id: str = Field(description="Unique identifier for the task, e.g. task_1")
    description: str = Field(description="Clear action-oriented task description")
    objective: str = Field(default="", description="Specific sub-goal this task aims to accomplish")
    expected_output: str = Field(default="", description="Description of expected deliverable/data from this step")
    suggested_tool: str = Field(description="Name of the tool suggested for executing this step")
    dependencies: List[str] = Field(
        default_factory=list,
        description="IDs of prerequisite tasks that must be completed before this step"
    )
    tool_input: Dict[str, Any] = Field(default_factory=dict, description="Input parameters passed to the tool")
    status: TaskStatus = Field(default=TaskStatus.PENDING, description="Current execution status")
    result: Optional[Any] = Field(default=None, description="Observed output from tool execution")
    error: Optional[str] = Field(default=None, description="Error message if task failed")
    retry_count: int = Field(default=0, description="Number of retry attempts made")


class Plan(BaseModel):
    """Dynamically generated sequence of tasks to achieve the user's research goal."""
    query: str = Field(description="Original research topic or query submitted by user")
    rationale: str = Field(description="Explanation of why this dynamic plan decomposition was selected")
    tasks: List[Task] = Field(default_factory=list, description="Sequence of subtasks to execute")
    current_task_index: int = Field(default=0, description="Index of task currently under execution")

    @classmethod
    def from_llm_plan(cls, llm_plan: LLMPlan) -> "Plan":
        """Factory constructor converting closed LLMPlan into runtime Plan."""
        return llm_plan.to_runtime_plan()


class ToolCall(BaseModel):
    """Structured declaration of a tool invocation request."""
    tool_name: str = Field(description="Name of registered tool to execute")
    arguments: Dict[str, Any] = Field(default_factory=dict, description="Validated argument map for the tool")
    purpose: str = Field(default="", description="Specific reason or goal for this tool call")


class Observation(BaseModel):
    """Structured record of the outcome of a tool execution step."""
    tool: str = Field(description="Name of tool that was executed")
    success: bool = Field(description="Whether the tool execution completed successfully")
    summary: str = Field(description="Concise summary of the result or failure")
    data_count: int = Field(default=0, description="Count of discrete items retrieved (e.g. results or chars)")
    error: Optional[str] = Field(default=None, description="Error message if execution failed")
    details: Dict[str, Any] = Field(default_factory=dict, description="Additional structured execution metadata")


class EvaluationDecision(BaseModel):
    """Assessment decision reached after evaluating the latest execution step."""
    decision: DecisionType = Field(description="Action to take next (continue, retry, replan, complete, fail)")
    reason: str = Field(description="Concise operational reason for the decision")
    confidence: float = Field(default=1.0, description="Confidence score [0.0 - 1.0]")
    next_action: str = Field(default="", description="Description of the subsequent planned action")


class SearchResultItem(BaseModel):
    """A single result item returned from a web search provider."""
    title: str = Field(description="Page or article title")
    url: str = Field(description="Canonical URL of search result")
    snippet: str = Field(description="Short text summary or snippet")
    source: Optional[str] = Field(default=None, description="Source domain or publication name")
    published_at: Optional[str] = Field(default=None, description="Publication timestamp if available")
    relevance_score: Optional[float] = Field(default=None, description="Relevance score from provider if available")


class SearchResponse(BaseModel):
    """Structured response container for web search queries."""
    query: str = Field(description="Original search query string")
    results: List[SearchResultItem] = Field(default_factory=list, description="List of search result items")
    provider: str = Field(default="tavily", description="Name of search provider used")
    success: bool = Field(default=True, description="Whether the search request succeeded")
    error: Optional[str] = Field(default=None, description="Error message if search failed")


class FetchedPage(BaseModel):
    """Structured result returned by the page fetcher tool."""
    url: str = Field(description="Target URL requested")
    final_url: Optional[str] = Field(default=None, description="Final URL after following redirects")
    title: Optional[str] = Field(default=None, description="Page title extracted from DOM")
    content: str = Field(default="", description="Cleaned readable text content extracted from page")
    content_hash: str = Field(default="", description="SHA-256 hash of extracted text for deduplication")
    text_length: int = Field(default=0, description="Character count of extracted content")
    status_code: Optional[int] = Field(default=None, description="HTTP response status code")
    content_type: Optional[str] = Field(default=None, description="MIME content type header")
    success: bool = Field(default=True, description="Whether page fetching and extraction succeeded")
    error: Optional[str] = Field(default=None, description="Error message if fetching failed")
    fetched_at: str = Field(
        default_factory=lambda: datetime.now(timezone.utc).isoformat(),
        description="ISO 8601 UTC timestamp of fetch operation"
    )


class EvidenceItem(BaseModel):
    """A granular, traceable unit of research evidence extracted from an external source."""
    source_url: str = Field(description="URL source of the evidence")
    source_title: str = Field(description="Source document title")
    source_domain: Optional[str] = Field(default=None, description="Extracted domain of source")
    claim: str = Field(description="Atomic factual claim or statement")
    supporting_text: str = Field(description="Verbatim or close context supporting the claim")
    relevance_score: float = Field(default=1.0, ge=0.0, le=1.0, description="Relevance score [0.0 - 1.0]")
    content_hash: str = Field(description="SHA-256 hash of claim and supporting text for deduplication")
    evidence_type: str = Field(
        default="empirical",
        description="Type of evidence: empirical, statistical, architectural, benchmark, or theoretical"
    )
    extraction_reason: Optional[str] = Field(default=None, description="Rationale for extracting this excerpt")
    confidence: float = Field(default=1.0, ge=0.0, le=1.0, description="Extraction confidence score [0.0 - 1.0]")


class ResearchEvidence(BaseModel):
    """Structured evidence excerpt extracted from an external source (legacy compatibility)."""
    source_url: str = Field(description="URL source of the evidence chunk")
    title: str = Field(description="Source document title")
    content_chunk: str = Field(description="Extracted relevant text excerpt")
    relevance_score: float = Field(default=1.0, description="Estimated relevance score [0.0 - 1.0]")


class KeyFinding(BaseModel):
    """A distinct factual finding derived from gathered research evidence."""
    claim: str = Field(description="Core assertion or factual discovery")
    explanation: str = Field(description="Contextual explanation and evidence synthesis")
    supporting_source_urls: List[str] = Field(default_factory=list, description="Source URLs backing this finding")


class SourceCitation(BaseModel):
    """Traceable citation for a research source."""
    url: str = Field(description="Canonical URL of source")
    title: str = Field(description="Title of page or document")
    domain: Optional[str] = Field(default=None, description="Domain name of source")
    relevant_excerpts_count: int = Field(default=1, description="Number of evidence chunks extracted from source")


class ResearchReport(BaseModel):
    """Final structured report synthesized at the conclusion of research."""
    research_question: str = Field(description="The primary research objective or user prompt")
    topic: Optional[str] = Field(default=None, description="Main research topic")
    executive_summary: str = Field(description="High-level synthesis and executive overview")
    key_findings: List[KeyFinding] = Field(default_factory=list, description="Structured factual findings with citations")
    important_evidence: List[EvidenceItem] = Field(default_factory=list, description="Curated list of key evidence items")
    sources: List[SourceCitation] = Field(default_factory=list, description="List of referenced sources")
    actionable_insights: List[str] = Field(default_factory=list, description="Practical takeaways, recommendations, or next steps")
    limitations: List[str] = Field(default_factory=list, description="Uncertainties, conflicting evidence, or gaps in retrieved information")

    @property
    def key_points(self) -> List[str]:
        return [f.claim for f in self.key_findings]

    @property
    def important_findings(self) -> List[str]:
        return [f"{f.claim}: {f.explanation}" for f in self.key_findings]
